import { Geist, Geist_Mono, Noto_Sans } from "next/font/google";
import "./globals.css";
import NavBar from "./components/Navbar";
import DataContext  from './context/dataContext';
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const NotoSans = Noto_Sans({
  variable: "--font-Noto-Sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${NotoSans.variable} antialiased`}>
        <div className="flex min-h-screen flex-col bg-[#fafafa]">
          <NavBar />
          
          {/* المسافة بين الهيدر والبودي */}
          <main className="flex-grow pt-16 sm:pt-20">
   <DataContext>
            {children}
  </DataContext>
          </main>
        </div>
      </body>
    </html>
  );
}