import { Geist, Geist_Mono, Noto_Sans } from "next/font/google";
import "./globals.css";
import NavBar from "./componants/NavBar";
import Footer from "./componants/footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
export const NotoSans = Noto_Sans({
  variable: "--font-Noto-Sans",
  subsets: ["latin"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${NotoSans.variable} antialiased`}
      >
<NavBar />
        {children}
      </body>
    </html>
  );
}
